stages:

- stage: build
  dependsOn: []
  displayName: Build
  jobs:
  - job: Windows_NT
    timeoutInMinutes: 90
    pool:
      name: NetCore-Public          
      demands: ImageOverride -equals 1es-windows-2019-open

    variables:

    steps:
    - checkout: self
      clean: true

    - task: UseDotNet@2
      displayName: install SDK
      inputs:
        packageType: sdk
        useGlobalJson: true
        includePreviewVersions: false
        workingDirectory: $(Build.SourcesDirectory)
        installationPath: $(Build.SourcesDirectory)/.dotnet
