stages:

- stage: build
  dependsOn: []
  displayName: Build
  jobs:
  - job: Windows_NT
    timeoutInMinutes: 90
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self
      clean: true

    - task: UseDotNet@2
      displayName: install SDK
      inputs:
        packageType: sdk
        useGlobalJson: true
        includePreviewVersions: true
        workingDirectory: $(Build.SourcesDirectory)
        installationPath: $(Build.SourcesDirectory)/.dotnet
